version: "3.8"

services:
  postgres:
    image: postgres:12.4-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pubsub
      POSTGRES_USER: pubsub
      POSTGRES_DB: pubsub
